version: "3.8"

networks:
  els:
    driver: bridge

services:
  setup:
    image: elasticsearch:${ELASTIC_VERSION}
    user: "0"
    command: >
      bash -c '
        echo "Waiting for Elasticsearch";
        until curl -s ${ELASTIC_URL} | grep -q "missing authentication credentials"; do sleep 10; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" ${ELASTIC_URL}/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "Done";
      '
    volumes:
      - ${VOLUMES_PATH}/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - els

  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=els
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=basic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - els
    ports:
      - "9200:9200"
    depends_on:
      - setup

  kibana:
    image: kibana:${ELASTIC_VERSION}
    container_name: kibana
    environment:
      - server.name=kibana
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_HOSTS=${ELASTIC_URL}
      - monitoring.ui.container.elasticsearch.enabled=true
    ports:
      - "5601:5601"
    networks:
      - els
    depends_on:
      - elasticsearch