filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /metrics/host_metrics_app.log
    fields:
      service: host_metrics_app

output.logstash:
  hosts: ["logstash:5044"]
  ssl.certificate_authorities: ["config/certs/logstash/ca.crt"]
  ssl.certificate: "config/certs/logstash/logstash.crt"
  ssl.key: "config/certs/logstash/logstash.key"