global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
          
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    scheme: https
    tls_config:
      #cert_file: /etc/prometheus/certs/prometheus.crt
      #key_file: /etc/prometheus/certs/prometheus.key
      ca_file: /etc/ssl/cert/ca.crt
    basic_auth:
      username: 'admin'
      password_file: /run/secrets/prometheus_password
    static_configs:
      - targets: ["localhost:9090"]