tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

basic_auth_users:
  admin: $2a$12$U2xDWd9leoyCVDlHQCLNL.cZZXalAhD63u.ywCBHOvRTTv1UcrjaW